apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cdn
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: nginx-cdn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cdn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-cdn
  template:
    metadata:
      labels:
        app: nginx-cdn
    spec:
      containers:
        - name: nginx-cdn
          image: snpsuen/nginx-cdn:v01
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cdn-vol
              mountPath: /var/cdn/cache
      volumes:
        - name: cdn-vol
          persistentVolumeClaim:
            claimName: cdn-pvc
