apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: pytorch-simple-trainjob
  namespace: default # Or the namespace where your runtime will live
spec:
  runtimeRef:
    kind: TrainingRuntime
    name: pytorch-simple-runtime
